ktor:
  deployment:
    port: 8080
    sslPort: 8443

  application:
    modules:
      - com.whatever.ApplicationKt.module
  security:
    ssl:
      keyAlias: "kate-media-test"
      keyStorePassword: 123456
      keyStore: "ktor.keystore"
      privateKeyPassword: 123456

postgres:
  url: "jdbc:postgresql://localhost:5432/postgres"
  user: postgres
  password: pwd


hikari:
  driverClassName: org.postgresql.Driver
  maximumPoolSize: 50
  transactionIsolation: TRANSACTION_READ_COMMITTED
  connectionTimeout: 30000
  idleTimeout: 600000
  maxLifetime: 1800000
  minimumIdle: 5
  poolName: HikariPool